# Generated by Django 5.2.5 on 2025-08-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
