# Generated by Django 5.2.5 on 2025-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="recipients",
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="mailing.recipientmailing", verbose_name="Получатели"
            ),
        ),
    ]
