# Generated by Django 5.2.5 on 2025-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_remove_mailing_recipients_mailing_recipients"),
        ("recipients", "0002_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="recipients.recipient", verbose_name="Получатели"
            ),
        ),
        migrations.DeleteModel(
            name="RecipientMailing",
        ),
    ]
