# Generated by Django 5.2.5 on 2025-08-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_recipients_delete_recipientmailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_delete_mailing", "Удаление рассылки"),
                    ("can_update_mailing", "Изменение рассылки"),
                    ("can_create_mailing", "Создание рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
