# Generated by Django 5.2.5 on 2025-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="email_status",
            field=models.TextField(default="", verbose_name="Текстовый статус"),
            preserve_default=False,
        ),
    ]
