# Generated by Django 5.2.5 on 2025-08-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_mailing_email_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
    ]
