# Generated by Django 5.2.5 on 2025-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailing_options"),
        ("recipients", "0007_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="recipients.recipient", verbose_name="Получатели сообщения"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status_ending",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
