# Generated by Django 5.2.5 on 2025-08-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0005_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("can_all_view_recipients", "Просмотр всех получателей"),
                    ("can_delete_recipient", "Удаление получателя"),
                    ("can_create_recipient", "Создание получателя"),
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
