# Generated by Django 5.2.5 on 2025-08-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0006_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
    ]
