# Generated by Django 5.2.5 on 2025-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar/", verbose_name="Аватар"
            ),
        ),
    ]
