# Generated by Django 5.2.5 on 2025-08-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_all_view_users", "Просмотр всех пользователей"),
                    ("can_block_user", "Блокировка пользователя"),
                    ("can_off_mailing", "Отключение рассылки"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
