# Generated by Django 5.2.5 on 2025-08-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_country_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block_user", "Блокировка пользователя"),
                    ("can_off_mailing", "Отключение рассылки"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
